### ISSUE TITLE
Loading seems to fail

### ISSUE THREAD

**Issue by brandonweiss** [danielpclark/faster_path#18] opened 2016-06-13 23:44 UTC
I installed the latest Rust release with `brew install rust`. Then added `faster_path` to a really large Rails 4.2 app. `bundle install` works, but when booting the environment with `time bundle exec rake environment` I get:

```
rake aborted!
LoadError: Could not open library '/opt/boxen/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faster_path-0.0.9/target/release/libfaster_path.dylib': dlopen(/opt/boxen/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faster_path-0.0.9/target/release/libfaster_path.dylib, 5): image not found
/Users/joannepham/src/intercom/config/application.rb:13:in `<top (required)>'
/Users/joannepham/src/intercom/Rakefile:4:in `require'
/Users/joannepham/src/intercom/Rakefile:4:in `<top (required)>'
bin/bundle:3:in `load'
bin/bundle:3:in `<main>'
(See full trace by running task with --trace)
bundle exec rake environment  4.78s user 2.43s system 92% cpu 7.821 total
```

P.S. I'm on a Mac.

**Comment by danielpclark** [comment] 2016-06-13 23:46
Thanks!  My clean up code in Rake removed the `dylib`.  I just now added an update to master https://github.com/danielpclark/faster_path/commit/9c52c52a590549845d2c55038867301117a8c152  Can you git clone and run `rake build_src && rake_clean` and tell me what's in the target/release folder?

**Comment by brandonweiss** [comment] 2016-06-13 23:49
```
❯ rake build_src; and rake clean; and ls target/release/
Building extension...
build                deps                 examples             libfaster_path.dylib native
```

**Comment by danielpclark** [comment] 2016-06-13 23:52
Ålright, I'm going to release 0.1.0 now for Mac support. :smile: *crosses fingers*

**Comment by brandonweiss** [comment] 2016-06-13 23:53
![hold on to your butts](https://cloud.githubusercontent.com/assets/4727/16026979/4d449fa6-3187-11e6-8318-98bfccea84d4.gif)

**Comment by danielpclark** [comment] 2016-06-13 23:57
[0.1.0](https://github.com/danielpclark/faster_path/tree/v0.1.0) is out.  Let me know if it build for you.

**Comment by danielpclark** [comment] 2016-06-14 01:40
I'm going to close this now.  Feel free to reopen this if you're having issues.

Mac's `dylib` support has been added.

**Comment by danielpclark** [comment] 2016-06-14 17:59
Re-opening.  This has been still confirmed by another user.

**Comment by bartoszkopinski** [comment] 2016-06-20 14:13
@danielpclark getting the same on OS X and codeship.com
@pik I believe the missing step is to install the gem from it's source. Would be nice to add this to the readme:

```
cargo build --release
gem build faster_path.gemspec
gem install faster_path-0.1.5.gem
```

**Comment by danielpclark** [comment] 2016-06-20 16:40
@bartoszkopinski The `cargo build --release` is a rake command handled in the `extconf.rb` file which is run during gem installation.  The library files aren't actually packaged in the gem you built but rather are built when the gem is installed by running the two rake commands `rake build_src && rake clean_src` .  For some reason on the Mac OS these rake commands aren't getting called during the installation process  ( issue #20 ).

**Comment by danielpclark** [comment] 2016-06-20 16:41
@pik can you give more details?

**Comment by pik** [comment] 2016-06-20 16:44
It seems to be because not all distributions bundle cargo with the rust
package and there is no exit status check on the cargo command which builds
the target libs.

**Comment by danielpclark** [comment] 2016-06-20 16:47
According to https://crates.io/install
> Rust comes with Cargo by default, so the easiest way to get Cargo is to install Rust via the official binary installers.

**Comment by pik** [comment] 2016-06-20 16:54
Yes, I know it's bundled with the binary but not all distributions follow
that convention (I'm going to guess homebrew for osx might not? Archlinux
doesn't). Simple solution is to check exit status / which cargo and return
an appropriate message to the user.

**Comment by danielpclark** [comment] 2016-06-20 16:56
Love the idea!

**Comment by danielpclark** [comment] 2017-03-02 06:28
I've written an AssetResolution module that will build the library on require if it wasn't built during gem install.  If that fails it will error out with a very clear message as to why.

Also I've added OSX testing with TravisCI and it passes.  So I'm closing this issue.

**Closed by danielpclark** 2017-03-02 06:28 UTC
Labels: bug, Mac
