### ISSUE TITLE
Pre-built binaries to remove the `rustc` dependency?

### ISSUE THREAD

**Issue by steveklabnik** [danielpclark/faster_path#34] opened 2016-06-17 10:41 UTC
Have you considered uploading pre-built binaries so that users don't need rustc installed? I would be willing to contribute a patch.

**Comment by malept** [comment] 2016-06-17 15:04
I've been working on a set of rake tasks that make it easy for developers to do just that: https://github.com/malept/thermite (thanks for the kick in the pants to actually make it public).

**Comment by danielpclark** [comment] 2016-06-17 16:29
I do like the idea.  As I understand it you will need to have a build for each OS type and maybe some variations of them?  Also the source of the binaries needs to be trusted.  So a trusted binary source with some gpg signatures?  What are your thoughts?  IMHO it's easier to trust the source code you get and see than the binaries packaged with/for it.

**Comment by Ryman** [comment] 2016-06-17 16:34
Might be a good use case for https://github.com/japaric/rust-everywhere to build your binaries which could give a decent value of trust.

**Comment by d-unseductable** [comment] 2016-07-08 19:31
> As I understand it you will need to have a build for each OS type and maybe some variations of them?

I believe it should be built and linked not only for OS, but for OS+ruby_version, like

```
...
x86_64-apple-darwin + ruby 2.3.0
x86_64-apple-darwin + ruby 2.3.1

...
i686-apple-darwin + ruby 2.3.0
i686-apple-darwin + ruby 2.3.1
...

etc
```

**Comment by malept** [comment] 2016-07-08 19:34
> I believe it should be built and linked not only for OS, but for OS+ruby_version

That is correct. I should update `rusty_blank` to do that.

**Comment by malept** [comment] 2016-07-08 19:35
However you should only need to build for minor ruby versions, not patch-level.

**Comment by d-unseductable** [comment] 2016-07-08 19:59
I'm not sure about pre-2.3 versions, for now I've tried with `2.3.0` and `2.3.1` (Mac OS X)

You can try to reproduce it locally.

1. Set ruby version to `2.3.0`
2. Build extension
3. Set ruby version to `2.3.1`
4. Run application

For me it fails with segfault :(

**Comment by malept** [comment] 2016-07-08 20:24
This is what I'm basing my statement on:

Several native Ruby extensions (like FFI and mysql2) provide binary gems for Windows Ruby builds. If  you look inside these gems, you'll see that it provides one native extension per minor Ruby version. In the case of `mysql2-0.4.4-x64-mingw32.gem`:

```
lib/mysql2/2.0/mysql2.so
lib/mysql2/2.1/mysql2.so
lib/mysql2/2.2/mysql2.so
lib/mysql2/2.3/mysql2.so
```

(I think the `.so` naming is a quirk of `rake-compiler`, but I'd have to check.)

**Comment by danielpclark** [comment] 2016-07-08 23:09
@d-unseductable, @malept  As I understand it with RVM when you switch Ruby versions it will say that the gem isn't installed.  Installing the gem for the new Ruby patch version should recompile the asset.  See how current extensions are managed in RVM path on [issue 71#comment](https://github.com/danielpclark/faster_path/issues/71#issuecomment-227648247) .  RVM will have separate gems per minor patch versions and seeing a segfault as you've demonstrated @d-unseductable leads me to believe that there should be builds for all "supported" patch versions.

We should probably follow RVM's example for Ruby builds.  Check for binary if it's available and if not download the source and compile it. Although in our case we shouldn't need to download the source as it's already in the gem.

I'm not sure how other Ruby version managers handle gem storage but if segfaults are possible with patch versions I would seriously hope they keep them separate.

**Comment by malept** [comment] 2016-07-08 23:25
Currently in Thermite, the check is the other way: if `cargo` is available, compile the extension. Otherwise (if the project enabled it), look for a binary. If a binary isn't found (or searching for binaries is disabled), an error message is displayed saying "Install Rust to use this extension".

**Comment by danielpclark** [comment] 2016-07-08 23:43
@malept I'm not against that.  That would save against server hosting usage (which I haven't considered yet).

**Comment by danielpclark** [comment] 2018-03-04 02:52
@malept I've done what seems to be needed but I may need your help.  I've merged your Thermite PR and included the Github credentials.  Thermite output messages on Travis CI says it's building and deploying but the releases don't seem to be showing up.  Only the source code archives are there.

Since TravisCI isn't outputting any more information than:

```
Installing deploy dependencies
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.14.0
Successfully installed public_suffix-3.0.2
Successfully installed addressable-2.5.2
Successfully installed sawyer-0.8.1
Successfully installed octokit-4.6.2
6 gems installed
Successfully installed mime-types-2.99.3
1 gem installed

Logged in as Daniel P. Clark
Deploying to repo: danielpclark/faster_path
Current tag is: v0.3.0

Preparing deploy

Deploying application

Done. Your build exited with 0.
```
I don't really know where it could have gone wrong.

**Comment by malept** [comment] 2018-03-05 02:45
@danielpclark It looks like you need to call `bundle exec rake thermite:tarball`, either in `script` or `after_success`.

**Comment by danielpclark** [comment] 2018-03-05 02:47
Okay, and the conditional environment flags will still apply?

**Comment by malept** [comment] 2018-03-05 02:53
Looks like it.

**Closed** 2018-03-05 02:59 UTC
Labels: binary releases, enhancement
