### ISSUE TITLE
Rust's basename is slower than ruby's on my machine

### ISSUE THREAD

**Issue by gogainda** [danielpclark/faster_path#51] opened 2016-06-19 22:05 UTC
```
bench_rust_basename      0.391744        0.384262        0.389821        0.395799        0.388389
bench_ruby_basename      0.343923        0.347006        0.347610        0.341183        0.340708
```

**Comment by danielpclark** [comment] 2016-06-19 23:22
What version of Rust are you running?  Here are my numbers.  Rust is definitely faster.

`rustc --version`
rustc 1.9.0-nightly (526f2bf5c 2016-04-09)

```
bench_rust_basename	 0.163431	 0.162723	 0.162924	 0.162847	 0.162748
 PASS (0.85s) :: bench_rust_basename
bench_ruby_basename	 0.211582	 0.212547	 0.209508	 0.209389	 0.209801
 PASS (1.09s) :: bench_ruby_basename
```

**Comment by gogainda** [comment] 2016-06-19 23:23
rustc 1.11.0-nightly (5c2a5d449 2016-06-11)

**Comment by danielpclark** [comment] 2016-06-19 23:26
Are you compiling with `cargo build --release` ?  Because if you forget the `--release` flag it won't be optimized and will add debug stuff.

**Comment by danielpclark** [comment] 2016-06-19 23:30
I upgraded my Rust version.

`rustc --version`
**rustc 1.11.0-nightly (bb4a79b08 2016-06-15)**

```
bench_rust_basename	 0.162883	 0.165921	 0.161602	 0.162563	 0.160645
 PASS (0.85s) :: bench_rust_basename
bench_ruby_basename	 0.208703	 0.208496	 0.216547	 0.214996	 0.215486
 PASS (1.10s) :: bench_ruby_basename
```

It's still faster on my PC.  What kind of computer are you using and what OS?

**Comment by danielpclark** [comment] 2016-06-19 23:35
Also do you have a production environment you're targeting?  You may want to benchmark it there as well.

**Comment by glebm** [comment] 2016-06-19 23:35
What Ruby version are you using? Can't reproduce this with MRI 2.3.1 -O3.

**Comment by danielpclark** [comment] 2016-06-19 23:39
I'm at

    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]

@gogainda ?

**Comment by gogainda** [comment] 2016-06-19 23:42
ruby 2.2.0p0 (2014-12-25 revision 49005) [i686-linux]

**Comment by danielpclark** [comment] 2016-06-19 23:44
i686 means you're running a 32bit OS.  I wonder if all 32bit operating systems would be similarly affected.

**Comment by gogainda** [comment] 2016-06-19 23:55
so problem with 32bit OS?

**Comment by danielpclark** [comment] 2016-06-19 23:56
Maybe so.  We should be able to improve on this regardless.

**Comment by danielpclark** [comment] 2016-06-20 00:03
We should get some other operating system results on this as well.  Windows & Mac.

**Comment by danielpclark** [comment] 2016-06-20 00:08
With more feedback we can implement a modification on the refinements and monkey-patches.  If this is always true on 32 bit machines than we can add a flag to prevent the faster methods from being replaced.  If there are consistent identifiers we'll use those to ensure the fastest methods will be used.

**Comment by gogainda** [comment] 2016-06-20 00:10
Could it be a problem with rust being run on 32bit OS, instead of ruby?

**Comment by danielpclark** [comment] 2016-06-20 00:12
It's not a problem of Rust.  "I'm guessing" it has to do with Rust having optimizations for 64 bit operating systems.

**Comment by gogainda** [comment] 2016-06-20 00:15
If so, the solution could be to write more performant implementation of basename which would be fast even on 32bit OS?

**Comment by danielpclark** [comment] 2016-06-20 00:16
At this point that would have to be writing assembly code.  Which is not feasible.

**Comment by danielpclark** [comment] 2016-06-20 02:49
I think I've had a regression on this method. The latest release is now slower on my 64 bit system.  Perhaps it's something that's changed?

**Comment by danielpclark** [comment] 2016-06-20 03:40
I'll close this issue and open a new one.  Since there is a new mystery around this I'd like to have a clarified issue on it.

**Closed by danielpclark** 2016-06-20 03:40 UTC
Labels: 32 bit, Linux, Mac, needs feedback, Windows
